version: '2.1'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    expose: 
      - "2181"
  nimbus:
    image: helterscelter/storm-nimbus
    expose:
      - "3773"
      - "3772"
      - "6627"
    links: 
      - zookeeper:zk
    depends_on:
      - zookeeper
  supervisor:
    image: helterscelter/storm-supervisor
    expose:
      - "8000"
    links: 
      - nimbus:nimbus
      - zookeeper:zk
    depends_on:
      - zookeeper
  ui:
    image: helterscelter/storm-ui
    ports:
      - "49080:8080"
    links: 
      - nimbus:nimbus
      - zookeeper:zk
    depends_on:
      - zookeeper
      - nimbus
